### ISSUE TITLE
original instruction to install of package coq-ext-lib fails with the 8.10 switch

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#56] opened 2022-12-10 20:52 UTC
https://github.com/coq-community/coq-ext-lib/issues/131

How do I go around this? what is causing the issue?
```
(iit_synthesis) brando9~/proverbot9001 $ opam install -y coq-ext-lib

The following actions will be performed:
  ∗ install coq-ext-lib dev

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved coq-ext-lib.dev  (git+https://github.com/coq-community/coq-ext-lib#master)
[ERROR] The compilation of coq-ext-lib.dev failed at "make -j127 theories".

#=== ERROR while compiling coq-ext-lib.dev ====================================#
# context     2.1.3 | linux/x86_64 | ocaml-base-compiler.4.07.1 | https://coq.inria.fr/opam/extra-dev#2022-12-06 09:40
# path        ~/.opam/coq-8.10/.opam-switch/build/coq-ext-lib.dev
# command     /usr/bin/make -j127 theories
# exit-code   2
# env-file    ~/.opam/log/coq-ext-lib-1328047-92e9b2.env
# output-file ~/.opam/log/coq-ext-lib-1328047-92e9b2.out
### output ###
# [...]
# make[2]: *** [Makefile.coq:658: theories/Tactics/BoolTac.vo] Error 1
# make[2]: *** Waiting for unfinished jobs....
# File "./theories/Programming/With.v", line 59, characters 0-39:
# Warning: Declaring a scope implicitly is deprecated; use in advance an
# explicit "Declare Scope struct_scope.". [undeclared-scope,deprecated]
# File "./theories/Data/ListFirstnSkipn.v", line 51, characters 0-101:
# Error: This command does not support this attribute: global.
#
# make[2]: *** [Makefile.coq:658: theories/Data/ListFirstnSkipn.vo] Error 1
# make[1]: *** [Makefile.coq:321: all] Error 2
# make[1]: Leaving directory '/lfs/ampere4/0/brando9/.opam/coq-8.10/.opam-switch/build/coq-ext-lib.dev'
# make: *** [Makefile:7: theories] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build coq-ext-lib dev
└─
╶─ No changes have been performed
```

thought you'd might want to know

https://stackoverflow.com/questions/74756476/how-does-one-install-a-opam-coq-package-that-has-been-successfully-install-previ

**Comment by brando90** [comment] 2022-12-10 21:13
for now I am installing it with my 8.12 switch:
```
# - succeeded with 8.12 switch
opam install -y coq-ext-lib
```

but perhaps we should upgrade as many of the repos possible to 8.14? I can't install 8.14 for some reason so using 8.12 for now.

**Comment by HazardousPeach** [comment] 2022-12-11 22:48
It looks like a lot of these issues are the same issue, the coq project was updated, and then the script is out of date. Either they updated the opam entry to explicitly require the newer coq, in which case we get a constraints error back from opam, or they didn't update it, in which case opam tries to build it on older coq but runs into the source incompatibility. Maybe you could move all these into one issue about making the script more reliable? I think ultimately the way to go is pin a commit on the repos and not use opam for coq project dependencies. It looks like specifying commits directly never made it into opam https://github.com/ocaml/opam/issues/2762

**Comment by HazardousPeach** [comment] 2022-12-13 18:27
I'm going to close this since the cause and solution are the same as #55, so we can track discussion on this issue there.

**Closed by HazardousPeach** 2022-12-13 18:27 UTC
