### ISSUE TITLE
original instruction to install coq-simple-io fails with switch 8.10

### ISSUE THREAD

**Issue by brando90** [UCSD-PL/proverbot9001#58] opened 2022-12-10 21:16 UTC
The original instruction to install coq-simple-io fails with switch 8.10.

Error:
```
(iit_synthesis) brando9~/proverbot9001 $ opam install -y coq-simple-io
The following actions will be performed:
  ∗ install coq-ext-lib   dev   [required by coq-simple-io]
  ∗ install coq-simple-io 1.5.0
===== ∗ 2 =====

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved coq-ext-lib.dev  (no changes)
⬇ retrieved coq-simple-io.1.5.0  (https://github.com/Lysxia/coq-simple-io/archive/1.5.0.tar.gz)
[ERROR] The compilation of coq-ext-lib.dev failed at "make -j127 theories".

#=== ERROR while compiling coq-ext-lib.dev ====================================#
# context     2.1.3 | linux/x86_64 | ocaml-base-compiler.4.07.1 | https://coq.inria.fr/opam/extra-dev#2022-12-06 09:40
# path        ~/.opam/coq-8.10/.opam-switch/build/coq-ext-lib.dev
# command     /usr/bin/make -j127 theories
# exit-code   2
# env-file    ~/.opam/log/coq-ext-lib-1340121-a23a76.env
# output-file ~/.opam/log/coq-ext-lib-1340121-a23a76.out
### output ###
# [...]
# make[2]: *** [Makefile.coq:658: theories/Tactics/BoolTac.vo] Error 1
# make[2]: *** Waiting for unfinished jobs....
# File "./theories/Programming/With.v", line 59, characters 0-39:
# Warning: Declaring a scope implicitly is deprecated; use in advance an
# explicit "Declare Scope struct_scope.". [undeclared-scope,deprecated]
# File "./theories/Data/ListFirstnSkipn.v", line 51, characters 0-101:
# Error: This command does not support this attribute: global.
#
# make[2]: *** [Makefile.coq:658: theories/Data/ListFirstnSkipn.vo] Error 1
# make[1]: *** [Makefile.coq:321: all] Error 2
# make[1]: Leaving directory '/lfs/ampere4/0/brando9/.opam/coq-8.10/.opam-switch/build/coq-ext-lib.dev'
# make: *** [Makefile:7: theories] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build coq-ext-lib dev
└─
╶─ No changes have been performed
```

**Comment by brando90** [comment] 2022-12-10 21:17
Seems it succeeded with the 8.12 switch. I still can't use 8.14 and this pkg didn't force me to require 8.14 so 8.12 can be a good solution for now since it at least works. 

also, `coq-simple-io` does NOT appear in the coqgym projs splits. Is it only a dependency and we don't mine data from it?

**Comment by brando90** [comment] 2022-12-10 21:17
> Seems it succeeded with the 8.12 switch. I still can't use 8.14 and this pkg didn't force me to require 8.14 so 8.12 can be a good solution for now since it at least works.

output for full reference:
```
(iit_synthesis) brando9~/proverbot9001 $ eval $(opam env --switch=coq-8.12 --set-switch)
(iit_synthesis) brando9~/proverbot9001 $ opam install -y coq-simple-io
The following actions will be performed:
  ↘ downgrade ocamlfind                1.9.5 to 1.9.1 [required by coq-simple-io]
  ∗ install   ocaml-secondary-compiler 4.08.1-1       [required by ocamlfind-secondary]
  ∗ install   ocamlfind-secondary      1.9.1          [required by dune]
  ∗ install   dune                     3.6.1          [required by coq-simple-io]
  ∗ install   cppo                     1.6.9          [required by coq-simple-io]
  ∗ install   coq-simple-io            dev
===== ∗ 5   ↘ 1 =====

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved cppo.1.6.9  (cached)
⬇ retrieved ocaml-secondary-compiler.4.08.1-1  (cached)
⬇ retrieved dune.3.6.1  (cached)
⬇ retrieved ocamlfind.1.9.1  (cached)
⬇ retrieved ocamlfind-secondary.1.9.1  (cached)
⬇ retrieved coq-simple-io.dev  (git+https://github.com/Lysxia/coq-simple-io#master)
[WARNING] While removing ocamlfind.1.9.5: cannot revert:
  - permission change of:
      - [hash] man/man5
      - [hash] man/man3
      - [hash] man/man1
      - [hash] man
      - [hash] lib/ocaml
      - [hash] lib
      - [hash] bin

⊘ removed   ocamlfind.1.9.5
∗ installed ocamlfind.1.9.1
∗ installed ocaml-secondary-compiler.4.08.1-1
∗ installed ocamlfind-secondary.1.9.1
∗ installed dune.3.6.1
∗ installed cppo.1.6.9
∗ installed coq-simple-io.dev
Done.
```

**Comment by HazardousPeach** [comment] 2022-12-11 22:52
Yeah we don't mine data from coq-simple-io, it's just a dependency. The build error on its dependency is the same backwards compatibility issue as all the others with the global keyword. If you're able to move the things that depend on it to 8.12 instead, great.

**Comment by HazardousPeach** [comment] 2022-12-13 18:28
I'm going to close this since the cause and solution are the same as #55, so we can track discussion on this issue there.

**Closed by HazardousPeach** 2022-12-13 18:28 UTC
